import type SSignal from 'ssignal'

/** Custom application event recorded by the event collector. */
export interface MonitorEvent {
  /** Unique event id generated by the collector. */
  id: string
  /** Application-defined event label. */
  label: string
  /** Optional structured event payload. */
  data: Record<string, unknown> | null
  /** Unix timestamp in milliseconds for when the event was recorded. */
  timestamp: number
}

/** Retained custom event history and derived label counts. */
export interface EventSnapshot {
  /** Recent custom events, capped by `maxHistory`. */
  entries: MonitorEvent[]
  /** Event counts by label, derived from retained entries. */
  byLabel: Record<string, number>
}

/** Configuration for the event collector. */
export interface EventCollectorConfig {
  /** Maximum number of custom events to retain. */
  maxHistory: number
}

/** Public API exposed by the event collector. */
export interface IEventCollector {
  /** Signal containing retained events and derived label counts. */
  snapshot: SSignal<EventSnapshot>
  /** Signal set to the latest recorded event, or null before any event is recorded. */
  onEvent: SSignal<MonitorEvent | null>
  /** Clears retained events and derived label counts. */
  clearLog(): void
  /** Starts listening for events emitted by `emitMonitorEvent`. */
  start(): void
  /** Stops listening for custom monitor events. */
  stop(): void
  /** Stops the collector and releases owned resources. */
  destroy(): void
}
