import type SSignal from 'ssignal'

/** Captured metadata for one fetch or XMLHttpRequest request. */
export interface NetworkEntry {
  /** Unique entry id generated by the collector. */
  id: string
  /** Requested URL as seen by fetch or XMLHttpRequest. */
  url: string
  /** Uppercase HTTP method. */
  method: string
  /** HTTP status code, or 0 when the request failed before receiving a response. */
  status: number
  /** Request latency in milliseconds. */
  latency: number
  /** Response payload size in bytes when it can be measured. */
  payloadSize: number
  /** Request body size in bytes when it can be estimated. */
  requestSize: number
  /** Browser API used to initiate the request. */
  initiator: 'fetch' | 'xhr'
  /** Unix timestamp in milliseconds for when the request was recorded. */
  timestamp: number
  /** Error message when the request failed, otherwise null. */
  error: string | null
}

/** Rolling network statistics computed from requests recorded in the last five seconds. */
export interface NetworkWindow5s {
  /** Number of retained requests in the five-second window. */
  count: number
  /** Average latency in milliseconds for requests in the window. */
  avgLatency: number
  /** Total response payload size in bytes for requests in the window. */
  totalPayload: number
  /** Fraction of failed or HTTP 4xx/5xx requests, from 0 to 1. */
  errorRate: number
}

/** Retained network request history and rolling statistics. */
export interface NetworkSnapshot {
  /** Recent request entries, capped by `maxHistory`. */
  entries: NetworkEntry[]
  /** Statistics computed over recent requests from the last five seconds. */
  window5s: NetworkWindow5s
}

/** Configuration for the network collector. */
export interface NetworkCollectorConfig {
  /** Maximum number of request entries to retain. */
  maxHistory: number
  /** Optional predicate used to decide whether a URL should be recorded. */
  filter?: (url: string) => boolean
}

/** Public API exposed by the network collector. */
export interface INetworkCollector {
  /** Signal containing retained requests and rolling statistics. */
  snapshot: SSignal<NetworkSnapshot>
  /** Signal set to the latest recorded request, or null before any request is recorded. */
  onRequest: SSignal<NetworkEntry | null>
  /** Clears retained request entries. */
  clearLog(): void
  /** Replaces the URL filter used for future requests. */
  setFilter(fn: (url: string) => boolean): void
  /** Patches fetch and XMLHttpRequest when running in a browser. */
  start(): void
  /** Restores patched browser APIs. */
  stop(): void
  /** Stops the collector and releases owned resources. */
  destroy(): void
}
