import type SSignal from 'ssignal'

/** Supported Web Vitals metric names. */
export type WebVitalName = 'CLS' | 'FCP' | 'INP' | 'LCP' | 'TTFB'

/** Serializable Web Vitals metric captured from the `web-vitals` package. */
export interface WebVitalMetric {
  /** Metric name. */
  name: WebVitalName
  /** Current metric value. Units depend on the metric: CLS is unitless, others are milliseconds. */
  value: number
  /** Delta from the previous report for the same metric instance. */
  delta: number
  /** Rating based on Web Vitals thresholds. */
  rating: 'good' | 'needs-improvement' | 'poor'
  /** Stable id generated by `web-vitals` for deduplication. */
  id: string
  /** Navigation type associated with the metric. */
  navigationType: string
  /** Unix timestamp in milliseconds for when the metric was recorded. */
  timestamp: number
}

/** Latest Web Vitals values and retained metric reports. */
export interface WebVitalsSnapshot {
  /** Latest Cumulative Layout Shift metric. */
  cls: WebVitalMetric | null
  /** Latest First Contentful Paint metric. */
  fcp: WebVitalMetric | null
  /** Latest Interaction to Next Paint metric. */
  inp: WebVitalMetric | null
  /** Latest Largest Contentful Paint metric. */
  lcp: WebVitalMetric | null
  /** Latest Time to First Byte metric. */
  ttfb: WebVitalMetric | null
  /** Recent metric reports, capped by `maxHistory`. */
  entries: WebVitalMetric[]
}

/** Configuration for the Web Vitals collector. */
export interface WebVitalsCollectorConfig {
  /** Maximum number of metric reports to retain. */
  maxHistory: number
  /** Whether to report metric updates as values change. Defaults to true. */
  reportAllChanges: boolean
}

/** Public API exposed by the Web Vitals collector. */
export interface IWebVitalsCollector {
  /** Signal containing latest Web Vitals values and retained reports. */
  snapshot: SSignal<WebVitalsSnapshot>
  /** Signal set to the latest Web Vitals metric report, or null before any metric is reported. */
  onMetric: SSignal<WebVitalMetric | null>
  /** Clears retained metric reports and latest values. */
  clearLog(): void
  /** Starts Web Vitals observers when running in a browser. */
  start(): void
  /** Stops accepting future Web Vitals reports from registered callbacks. */
  stop(): void
  /** Stops the collector and releases owned resources. */
  destroy(): void
}
